---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: instalamos apache
    package:
      name: httpd
      state: latest
  - name: iniciamos servicio y configuramos en arranque
    service:
      name: httpd
      state: started
      enabled: yes
  - name: creamos la pagina de iniciamos
    file:
      path: /var/www/html/index.html
      state: touch
  - name: añadimos contenido al fichero
    copy:
      content: "Hola!!"
      dest: /var/www/html/index.html